### ISSUE TITLE
Problem with one particular seed test

### ISSUE THREAD

**Issue by kurshakuz** [AISG-Technology-Team/Diner-Dash-Workshop#10]
Can't figure out what is the problem. Firstly, sought that problem could be with my model, but I tried different ones and issue persists.

![Screenshot from 2020-08-04 18-19-49](https://user-images.githubusercontent.com/28868430/89293138-382ec000-d67f-11ea-80dc-bfd03d0aa991.png)

**Comment by BenjaminChua** [comment]
Did you change the randomseeds in test()?

**Comment by kurshakuz** [comment]
@BenjaminChua no, where can I get it? I have found nothing in my mailbox.

**Comment by BenjaminChua** [comment]
It is in this repo: https://github.com/AISG-Technology-Team/Diner-Dash-Workshop/blob/master/randomSeeds.py

**Comment by kurshakuz** [comment]
@BenjaminChua thank you!
