### ISSUE TITLE
DQN algorithm not suitable for vectorized environment

### ISSUE THREAD

**Issue by yihui98** [AISG-Technology-Team/Diner-Dash-Workshop#3]
Hi I was running this piece of code when I ran into this error.

dqn_model = DQN('MlpPolicy', env, verbose=1, **kwargs)

ValueError: Error: the model requires a non vectorized environment or a single vectorized environment.

Does this mean that the environment we are using is a vectorized environment? and if it is, is there any way to convert it into the above instances?

**Comment by BenjaminChua** [comment]
Yes, the original code (PPO) uses vectorized environments. Please look at the sample code in the stable baselines documentation for help regarding the use of DQN.

**Comment by yihui98** [comment]
ok thank you!
