### ISSUE TITLE
Error: Module not found when importing PPO2 from stable_baselines

### ISSUE THREAD

**Issue by Prachi-Agr** [AISG-Technology-Team/Diner-Dash-Workshop#4]
I am getting the following error while importing PPO2- from stable_baselines import PPO2
ModuleNotFoundError: No module named 'tensorflow.contrib'

I am using tensorflow1 as per the template provided.
Thank you

**Comment by BenjaminChua** [comment]
I would suggest restarting the runtime and trying the installation of stable baselines once again. Please let me know how that goes.

**Comment by Prachi-Agr** [comment]
That worked. Thank you.
