### ISSUE TITLE
Error when running the test

### ISSUE THREAD

**Issue by yihui98** [AISG-Technology-Team/Diner-Dash-Workshop#5]
We have trained the model using number of variables = 24 and while testing, we encountered this error. We need guidance on how to resolve this issue. Thanks

AssertionError: Error: the environment passed must have the same number of environments as the model was trained on.This is due to ACER not being capable of changing the number of environments.

**Comment by BenjaminChua** [comment]
You can try adding n_envs as a parameter in the testing function:

# Vectorize environment
env = make_vec_env(env_id="diner_dash:DinerDash-v0", n_envs=n_envs, wrapper_class=OneHotWrapper, seed=seed)

Hope it works

**Comment by yihui98** [comment]
It worked, but now there is another error.


20   while not done:
     21     action, _states = acer_model.predict(obs)
---> 22     action_list.append(action.item())
     23     obs, rewards, done, info = env.step(action)
     24     sum_rewards += rewards

ValueError: can only convert an array of size 1 to a Python scalar

**Comment by BenjaminChua** [comment]
One work around would be to train with just 1 env. You can try this in the meanwhile if it gives a sufficiently good reward

**Comment by yihui98** [comment]
Ok thanks, we will do that

**Comment by BenjaminChua** [comment]
![Screenshot 2020-08-04 at 5 54 09 PM](https://user-images.githubusercontent.com/39892713/89280657-8215a700-d67b-11ea-94ee-043a454f8774.png)
Hi this is what I found. Since you trained on n_envs = 24, the test function should also provide n_envs to make_vec_env. This is not required in PPO as it is flexible enough. For other algorithms, you would need to change the _while not done_ portion of the test function. You would need to figure out if this list of 24 numbers are the first action from 24 (same seed) environments or the first 24 actions of 1 environment. I am leaning towards the former but you would need to confirm that.

**Comment by BenjaminChua** [comment]
![Screenshot 2020-08-04 at 6 17 13 PM](https://user-images.githubusercontent.com/39892713/89282848-b9d21e00-d67e-11ea-8d29-87b01beaaf01.png)
I believed that this is the easiest way to go about the problem. I have not fully tested this solution so please let me know if it does not work. Basically remove the env=env in .load, it is only necessary for retraining. also remove the n_envs parameter in make_vec_env.

Hope this help!

**Comment by ai4uteam** [comment]
after remove the env=env and n_envs at make_vec_env, for my case i able to generate the json file. however i cant see what is the reward. is it consider ok?

**Comment by BenjaminChua** [comment]
Just to be sure, using test() function of the colabs notebook did not generate an average reward?

**Comment by ai4uteam** [comment]
it is working!

thanks for the help!it is my bad, i need scroll down. the average reward shown after long list of message.

**Comment by BenjaminChua** [comment]
![Screenshot 2020-08-04 at 6 41 38 PM](https://user-images.githubusercontent.com/39892713/89284972-23076080-d682-11ea-8234-54d41c5854dd.png)
It should display before the action lists

**Comment by yihui98** [comment]
> 
> 
> ![Screenshot 2020-08-04 at 6 17 13 PM](https://user-images.githubusercontent.com/39892713/89282848-b9d21e00-d67e-11ea-8d29-87b01beaaf01.png)
> I believe that this is the easiest way to go about the problem. I have not fully tested this solution so please let me know if it does not work. Basically remove the env=env in .load, it is only necessary for retraining. also remove the n_envs parameter in make_vec_env.
> 
> Hope this help!

Ok thanks everyone, it is working well ! Appreciate your efforts!
