### ISSUE TITLE
Error: Kernel is crashing continually when I restart and run all the cells in the notebook, after updating randomSeeds function

### ISSUE THREAD

**Issue by turtle-patronus** [AISG-Technology-Team/Diner-Dash-Workshop#7]
I updated the randomSeeds functions according to the file posted in the repo. However, each time I reach the functions for the PPO algorithm in the Self Implemented/Adapted Models section, my session crashes. It was running just fine prior to updating the randomSeeds function.

I'm getting a session runtime error. Following are the error messages in the runtime log:

Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.021841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/device:GPU:0 with 10805 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.021768: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.020912: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.019912: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.019650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0: N
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.019632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186] 0
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.019565: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.017616: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.017519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.016446: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.015422: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.015178: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.010800: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.009190: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.006927: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.006380: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.004449: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.001796: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Aug 4, 2020, 3:12:32 PM | WARNING | pciBusID: 0000:00:04.0
Aug 4, 2020, 3:12:32 PM | WARNING | name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.001177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:32.000296: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:31.999927: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Tesla K80, Compute Capability 3.7
Aug 4, 2020, 3:12:32 PM | WARNING | 2020-08-04 09:42:31.999873: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2d3f480 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
Aug 4, 2020, 3:12:31 PM | WARNING | 2020-08-04 09:42:31.998827: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
Aug 4, 2020, 3:12:31 PM | WARNING | 2020-08-04 09:42:31.926876: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
Aug 4, 2020, 3:12:31 PM | WARNING | 2020-08-04 09:42:31.924196: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
Aug 4, 2020, 3:12:31 PM | WARNING | 2020-08-04 09:42:31.924165: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2d3f2c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
Aug 4, 2020, 3:12:31 PM | WARNING | 2020-08-04 09:42:31.923580: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz

**Comment by BenjaminChua** [comment]
Could you please screenshot the implementation of the randomseeds?

**Comment by turtle-patronus** [comment]
Here is the screenshot:
![Screenshot 2020-08-04 at 3 23 23 PM](https://user-images.githubusercontent.com/50493083/89280580-723f9800-d666-11ea-8bba-21b6a29152e0.png)

**Comment by BenjaminChua** [comment]
Did you copy and paste into the test() function in the colab notebook?

**Comment by turtle-patronus** [comment]
Yes. Had updated it in the test() function.

![Screenshot 2020-08-04 at 3 37 40 PM](https://user-images.githubusercontent.com/50493083/89281954-710f6a80-d668-11ea-843e-fc95f622981b.png)

**Comment by BenjaminChua** [comment]
Is this on google colabs or a text editor

**Comment by turtle-patronus** [comment]
On google colabs

**Comment by BenjaminChua** [comment]
and removing the random seeds would allow the code to run again?

**Comment by turtle-patronus** [comment]
No, it keeps on crashing before I even reach the part with random seeds in the test function. It was working fine an hour ago when I hadn't made any changes to it.

**Comment by BenjaminChua** [comment]
have you tried restarting the runtime?

**Comment by turtle-patronus** [comment]
Yes, multiple times. Each time I restart the runtime and run all the cells, it is crashing.

**Comment by BenjaminChua** [comment]
Sorry so after these sets of warnings the whole notebook crashes? What happens if you skip the PPO section?

**Comment by turtle-patronus** [comment]
Yes. I excluded PPO and it's running. I guess I'll exclude it from the notebook. Still not sure what the issue with PPO was but that's okay.
