### ISSUE TITLE
from stable_baselines import GAIL, SAC fail, is it due to tensorflow version

### ISSUE THREAD

**Issue by Lolonon** [AISG-Technology-Team/Diner-Dash-Workshop#8]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-92ab6b5a320f> in <module>()
----> 1 from stable_baselines import GAIL, SAC

2 frames
/usr/local/lib/python3.6/dist-packages/stable_baselines/__init__.py in <module>()
      2 from stable_baselines.acer import ACER
      3 from stable_baselines.acktr import ACKTR
----> 4 from stable_baselines.deepq import DQN
      5 from stable_baselines.her import HER
      6 from stable_baselines.ppo2 import PPO2

/usr/local/lib/python3.6/dist-packages/stable_baselines/deepq/__init__.py in <module>()
----> 1 from stable_baselines.deepq.policies import MlpPolicy, CnnPolicy, LnMlpPolicy, LnCnnPolicy
      2 from stable_baselines.deepq.build_graph import build_act, build_train  # noqa
      3 from stable_baselines.deepq.dqn import DQN
      4 from stable_baselines.common.buffers import ReplayBuffer, PrioritizedReplayBuffer  # noqa
      5 

/usr/local/lib/python3.6/dist-packages/stable_baselines/deepq/policies.py in <module>()
      1 import tensorflow as tf
----> 2 import tensorflow.contrib.layers as tf_layers
      3 import numpy as np
      4 from gym.spaces import Discrete
      5 

ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by BenjaminChua** [comment]
https://github.com/AISG-Technology-Team/Diner-Dash-Workshop/issues/4#issue-672581084

You might find this closed issue useful
