### ISSUE TITLE
Extending deadline for issue

### ISSUE THREAD

**Issue by Prachi-Agr** [AISG-Technology-Team/Diner-Dash-Workshop#9]
Would it be possible to extend the deadline for submission? I faced some issues in internet connectivity. It would be really helpful if extension of deadline is possible.
Thank you

**Comment by BenjaminChua** [comment]
Hi Prachi, unfortunately we are unable to extend the deadline. This is to be fair to the other participants. Please ensure that your group minimally has a submission so that we can mark your attendance. Thanks

**Comment by BenjaminChua** [comment]
The submissions have closed. I shall also close this issue.
